Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian10"

  config.vm.provision "shell", inline: <<-SHELL
    ################################################################## 
    # update and install few packages
    ################################################################## 
    apt-get update
    apt-get install -y netcat-openbsd ipcalc net-tools arping ethtool
    apt-get install -y tcpdump tmate

    ################################################################## 
    # enable forwarding
    ################################################################## 
    # enable ipv4 packet forwarding // L3 router only
    echo 1 > /proc/sys/net/ipv4/ip_forward
    # enable ipv6
    echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6
    # enable ipv6 policy
    echo 0 > /proc/sys/net/ipv6/conf/all/disable_policy
    # enable ipv6 forwarding // L3 router only
    echo 1 > /proc/sys/net/ipv6/conf/all/forwarding
    
    ################################################################## 
    # create dedicated namespaces
    ################################################################## 
    ip netns add alice
    ip netns add bob
    ip netns add charly
    ip netns add david
    ip netns add eve

    ################################################################## 
    # create bridge and activate it
    ################################################################## 
    ip link add bridge0 type bridge
    ip link set bridge0 up

    ################################################################## 
    # create virtual interfaces with dedicated peer name
    ################################################################## 
    ip link add vetha0 type veth peer name vetha1
    ip link add vethb0 type veth peer name vethb1
    ip link add vethc0 type veth peer name vethc1
    ip link add vethd0 type veth peer name vethd1
    ip link add vethe0 type veth peer name vethe1
    # ip link add vethf0 type veth peer name vethf1

    ################################################################## 
    # add virtual interface in namespaces
    ################################################################## 
    ip link set netns alice dev vetha1
    ip link set netns bob dev vethb1
    ip link set netns charly dev vethc1
    ip link set netns david dev vethd1
    ip link set netns eve dev vethe1
    # ip link set netns fred dev vethf1

    ################################################################## 
    # plug interfaces to the the main bridge
    ################################################################## 
    ip link set master bridge0 dev vetha0
    ip link set master bridge0 dev vethb0
    ip link set master bridge0 dev vethc0
    ip link set master bridge0 dev vethd0
    ip link set master bridge0 dev vethe0
    # link set master bridge0 dev vethf0

    ################################################################## 
    # activate interfaces
    ################################################################## 
    ip link set up dev vetha0
    ip link set up dev vethb0
    ip link set up dev vethc0
    ip link set up dev vethd0
    ip link set up dev vethe0
    # ip link set up dev vethf0

    ################################################################## 
    # set ip address network and activate virtual interfaces
    ################################################################## 
    ip -n alice link set up vetha1
    ip -n alice address add 10.0.0.1/24 dev vetha1

    ip -n bob link set up vethb1
    ip -n bob address add 10.0.0.2/24 dev vethb1

    ip -n charly link set up vethc1
    ip -n charly address add 10.0.0.3/24 dev vethc1

    ip -n david link set up vethd1
    ip -n david address add 10.0.0.4/24 dev vethd1

    # ip -n eve link set up vethf1
    # ip -n eve address add 10.0.0.5/24 dev vethe1

    # ip -n fred link set up vethf1
    # ip -n fred address add 10.0.0.6/24 dev vethf1

    ################################################################## 
    # test
    ################################################################## 
    ip netns exec alice ping -c 1 10.0.0.2
    ip netns exec bob ping -c 1 10.0.0.3
    ip netns exec charly ping -c 1 10.0.0.4
    ip netns exec david ping -c 1 10.0.0.1
    # ip netns exec eve ping -c 1 10.0.0.1
    # ip netns exec fred ping -c 1 10.0.0.1

    ################################################################## 
    # extra-conf - connect a bridge to another bridge
    # layer 2 routing
    ################################################################## 
    # ip link add bridge1 type bridge
    # ip link set up dev bridge1
    # ip link add vethbr0 type veth peer name vethbr1
    # ip link set master bridge0 vethbr0
    # ip link set master bridge1 vethbr1
    # ip link set up vethbr0
    # ip link set up vethbr1
    # ip address add 10.0.0.254/24 dev bridge1
    # ping -c 1 10.0.0.1
    # ip netns exec alice ping -c 1 10.0.0.254

  SHELL
end
