Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian10"

  config.vm.provision "shell", inline: <<-SHELL
    ################################################################## 
    # update and install few packages
    ################################################################## 
    apt-get update
    apt-get install -y netcat-openbsd ipcalc net-tools arping ethtool
    apt-get install -y tcpdump tmate

    ################################################################## 
    # enable forwarding
    ################################################################## 
    # enable ipv4 packet forwarding // L3 router only
    echo 1 > /proc/sys/net/ipv4/ip_forward
    # enable ipv6
    echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6
    # enable ipv6 policy
    echo 0 > /proc/sys/net/ipv6/conf/all/disable_policy
    # enable ipv6 forwarding // L3 router only
    echo 1 > /proc/sys/net/ipv6/conf/all/forwarding
    
    ################################################################## 
    # create dedicated namespaces
    ################################################################## 
    ip netns add alice
    ip netns add bob
    ip netns add charly

    ################################################################## 
    # create bridge and activate it
    ################################################################## 
    ip link add bridge0 type bridge
    ip link set bridge0 up

    ################################################################## 
    # create virtual interfaces with dedicated peer name
    ################################################################## 
    ip link add vetha0 type veth peer name vetha1
    ip link add vetha2 type veth peer name vetha3

    ip link add vethb0 type veth peer name vethb1
    ip link add vethb2 type veth peer name vethb3

    ip link add vethc0 type veth peer name vethc1
    ip link add vethc2 type veth peer name vethc3

    ################################################################## 
    # add virtual interface in namespaces
    ################################################################## 
    ip link set netns alice dev vetha1
    ip link set netns alice dev vetha3

    ip link set netns bob dev vethb1
    ip link set netns bob dev vethb3

    ip link set netns charly dev vethc1
    ip link set netns charly dev vethc3

    ################################################################## 
    # create bond interfaces
    ################################################################## 
    ip link add bonda0 type bond
    ip -n alice link add bonda1 type bond

    ip link add bondb0 type bond
    ip -n bob link add bondb1 type bond

    ip link add bondc0 type bond
    ip -n bob link add bondc1 type bond

    ################################################################## 
    # plug interfaces to the the main bridge
    ################################################################## 
    ip link set master bonda0 dev vetha0
    ip link set master bonda0 dev vetha2
    ip -n alice link set master bonda1 dev vetha1
    ip -n alice link set master bonda1 dev vetha3

    ip link set master bondb0 dev vethb0
    ip link set master bondb0 dev vethb2
    ip -n bob link set master bondb1 dev vethb1
    ip -n bob link set master bondb1 dev vethb3

    ip link set master bondc0 dev vethc0
    ip link set master bondc0 dev vethc2
    ip -n charly link set master bondc1 dev vethc1
    ip -n charly link set master bondc1 dev vethc3


    ################################################################## 
    # create bridge and plug bond on it
    ################################################################## 
    ip link add bridge0 type bridge
    ip link set up dev bridge0
    ip link set master bridge0 dev bonda0
    ip link set master bridge0 dev bondb0
    ip link set master bridge0 dev bondc0

    ################################################################## 
    # activate all interfaces
    ################################################################## 
    ip link set up dev bonda0
    ip link set up dev vetha0
    ip link set up dev vetha2
    ip -n alice link set up dev bonda1
    ip -n alice link set up dev vetha1
    ip -n alice link set up dev vetha3

    ip link set up dev bondb0
    ip link set up dev vethb0
    ip link set up dev vethb2
    ip -n bob link set up dev bondb1
    ip -n bob link set up dev vethb1
    ip -n bob link set up dev vethb3

    ip link set up dev bondc0
    ip link set up dev vethc0
    ip link set up dev vethc2
    ip -n charly link set up dev bondc1
    ip -n charly link set up dev vethc1
    ip -n charly link set up dev vethc3

    ################################################################## 
    # set ip address network and activate virtual interfaces
    ################################################################## 
    ip -n alice address add 10.1.0.1/24 dev bonda1
    ip -n bob address add 10.1.0.2/24 dev bondb1
    ip -n charly address add 10.1.0.3/24 dev bondb1

    ################################################################## 
    # test
    ################################################################## 
    ip netns exec alice ping -c 1 10.1.0.2
    ip netns exec bob ping -c 1 10.1.0.3
    ip netns exec charly ping -c 1 10.1.0.1

    # remove disable one link for eachnamespace
    ip link set down vetha0
    ip link set down vethb0
    ip link set down vethc0

    ip netns exec alice ping -c 1 10.1.0.2
    ip netns exec bob ping -c 1 10.1.0.3
    ip netns exec charly ping -c 1 10.1.0.1
  SHELL
end
